In [1]:
from data_ashare import AShare , AShareData, AShareDataModule, AShareVaeData
import pandas as pd 
import numpy as np 




/home/zhongmuyao/miniconda3/envs/simlob/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
a = AShare(csv_path='../dataset/real_data/resampled/sz000001-level10.csv',
           resampled_path='../dataset/real_data/resampled',
           processed_path='../dataset/real_data/processed',
           balanced_path='../dataset/real_data/balanced',)


(55656,)

In [ ]:
ashare_data = AShareData(dataset_path="../dataset/real_data/balanced/sz000001-level10.csv")
balanced_data = AShareDataModule(ashare_data,batch_size=128)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 15: invalid continuation byte

In [2]:
ashare_vae_data = AShareVaeData(dataset_path="../dataset/real_data/balanced/sz000001-level10_balanced.npz")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 15: invalid continuation byte

In [4]:
train_loader = balanced_data.train_dataloader()



128

In [6]:
for batch in train_loader:
    X,y = batch 
    print("Data:",X.shape)
    print("Label:",y.shape)
    

Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Size([128, 100, 40])
Label: torch.Size([128])
Data: torch.Si

/Users/mythezone/miniconda3/envs/simlob/lib/python3.8/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 20 worker processes in total. Our suggested max number of worker in current system is 10 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(


TypeError: cannot pickle '_io.BufferedReader' object

In [3]:
def get_ordered_columns(level=10, direct=("Bid","Ask"), pv=("Price", "Volume"),index=True,price=True,volume=True):
    """
    Get the ordered columns for the level of the order book.
    """

    columns = []

    if index:
        columns.append("index")

    if price:
        for i in range(level,0,-1):
            columns.append(f"{direct[0]}{pv[0]}{i}")
        for i in range(1,level+1):
            columns.append(f"{direct[1]}{pv[0]}{i}")

    if volume:
        for i in range(level,0,-1):
            columns.append(f"{direct[0]}{pv[1]}{i}")
        for i in range(1,level+1):
            columns.append(f"{direct[1]}{pv[1]}{i}")

    return columns


price_columns = get_ordered_columns(index=False, price=True, volume=False)
volume_columns = get_ordered_columns(index=False, price=False, volume=True)
print(price_columns)
print(volume_columns)

['BidPrice10', 'BidPrice9', 'BidPrice8', 'BidPrice7', 'BidPrice6', 'BidPrice5', 'BidPrice4', 'BidPrice3', 'BidPrice2', 'BidPrice1', 'AskPrice1', 'AskPrice2', 'AskPrice3', 'AskPrice4', 'AskPrice5', 'AskPrice6', 'AskPrice7', 'AskPrice8', 'AskPrice9', 'AskPrice10']
['BidVolume10', 'BidVolume9', 'BidVolume8', 'BidVolume7', 'BidVolume6', 'BidVolume5', 'BidVolume4', 'BidVolume3', 'BidVolume2', 'BidVolume1', 'AskVolume1', 'AskVolume2', 'AskVolume3', 'AskVolume4', 'AskVolume5', 'AskVolume6', 'AskVolume7', 'AskVolume8', 'AskVolume9', 'AskVolume10']


In [4]:

price_data = a.data[price_columns].values
print(price_data.shape)
# 去掉所有nan值后的平均值
print(np.nanmean(price_data))
print(np.nanstd(price_data))

a.data[price_columns] = (a.data[price_columns] - np.nanmean(price_data))/np.nanstd(price_data)

print(a.data.head(10))

# data/dataset/real_data/processed/sz000001-level10_resampled_zscore_processed.csv

(1171534, 20)
13.667120707550932
2.4064234647897673
                  index  BidPrice10  BidPrice9  BidPrice8  BidPrice7  \
1   2019-01-02 09:30:03   -1.810621  -1.806465  -1.802310  -1.798154   
2   2019-01-02 09:30:06   -1.810621  -1.806465  -1.802310  -1.798154   
3   2019-01-02 09:30:09   -1.806465  -1.802310  -1.798154  -1.793999   
4   2019-01-02 09:30:12   -1.806465  -1.802310  -1.798154  -1.793999   
5   2019-01-02 09:30:15   -1.810621  -1.806465  -1.802310  -1.798154   
6   2019-01-02 09:30:18   -1.810621  -1.806465  -1.802310  -1.798154   
7   2019-01-02 09:30:21   -1.810621  -1.806465  -1.802310  -1.798154   
8   2019-01-02 09:30:24   -1.814776  -1.810621  -1.806465  -1.802310   
9   2019-01-02 09:30:27   -1.814776  -1.810621  -1.806465  -1.802310   
10  2019-01-02 09:30:30   -1.814776  -1.810621  -1.806465  -1.802310   

    BidPrice6  BidPrice5  BidPrice4  BidPrice3  BidPrice2  ...  AskVolume1  \
1   -1.793999  -1.789843  -1.785688  -1.781532  -1.777377  ...      3600.0   

In [5]:
a.normalize_data()

Processed Data saved to ../dataset/real_data/processed/sz000001-level10_zscore.csv


In [6]:
a.data.shape

(1171534, 41)

In [7]:
md.head(10)

0    25.025
1    25.065
2    25.060
3    25.065
4    25.065
5    25.065
6    25.065
7    25.055
8    25.015
9    24.925
dtype: float64

In [ ]:

print(len(md))
trend.tail(10)

1171688


1171678    31.675
1171679    31.680
1171680    31.680
1171681    31.680
1171682    31.680
1171683    31.680
1171684    31.680
1171685    31.680
1171686    31.680
1171687    31.680
dtype: float64

In [14]:
md.tail(10)

1171678    31.68
1171679    31.68
1171680    31.68
1171681    31.68
1171682    31.68
1171683    31.68
1171684    31.68
1171685    31.68
1171686    31.68
1171687    31.68
dtype: float64

In [15]:
import numpy as np 

In [50]:
trend = md.rolling(window=5,center=False).mean()
theta = 0.00003
sign = np.where(trend>md*(1+theta),1,np.where(trend<md*(1-theta),-1,0))
print(sign[:100])
ups = np.sum(sign==1)/len(sign)
downs = np.sum(sign==-1)/len(sign)
steady = np.sum(sign==0)/len(sign)
print(f"ups:{ups:.02},downs:{downs:.02},steady:{steady:.02}")

[ 0  0  0  0 -1 -1 -1  1  1  1  1  0  1 -1 -1 -1 -1 -1  1  1  1 -1 -1 -1
 -1 -1 -1 -1 -1 -1  0 -1  1  1  1  1  1  0  1  1  1  1  0 -1 -1 -1  1  1
  1  1  0  0  0  0  0 -1 -1 -1 -1 -1 -1  1  1  1  1  1  1  1  1  1  1  0
  1  1  1  1  1  1  1  1  1 -1  1  1 -1 -1 -1 -1 -1  1 -1 -1  1  1 -1 -1
  1  1  1  1]
ups:0.31,downs:0.31,steady:0.38


[ 0  0  0  0  0  0  0  0  0  1  1 -1  0  0 -1  0  0  0  0  1  0 -1  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0]


In [32]:
ups = np.sum(sign==1)/len(sign)
downs = np.sum(sign==-1)/len(sign)
steady = np.sum(sign==0)/len(sign)
print(f"ups:{ups:.02},downs:{downs:.02},steady:{steady:.02}")

ups:0.14,downs:0.0023,steady:0.86


In [51]:
a.data.describe()

index    BidPrice10     BidPrice9  \
count                        1171688  1.171613e+06  1.171613e+06   
mean   2019-07-04 19:43:31.475410176  2.771431e+01  2.772899e+01   
min              2019-01-02 09:30:00  0.000000e+00  0.000000e+00   
25%              2019-04-04 04:52:30  2.686000e+01  2.688000e+01   
50%              2019-07-05 00:15:00  2.873000e+01  2.874000e+01   
75%              2019-10-02 13:37:30  2.969000e+01  2.970000e+01   
max              2019-12-31 15:00:00  3.343000e+01  3.349000e+01   
std                              NaN  4.047901e+00  4.043424e+00   

          BidPrice8     BidPrice7     BidPrice6     BidPrice5     BidPrice4  \
count  1.171613e+06  1.171613e+06  1.171613e+06  1.171613e+06  1.171613e+06   
mean   2.774287e+01  2.775654e+01  2.777012e+01  2.778395e+01  2.779815e+01   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    2.689000e+01  2.690000e+01  2.692000e+01  2.693000e+01  2.694000e+01   
50%    2.876000e+01  2.877000e+01  2.878000e+01  2.879000e+01  2.880000e+01   
75%    2.971000e+01  2.972000e+01  2.973000e+01  2.975000e+01  2.976000e+01   
max    3.350000e+01  3.351000e+01  3.353000e+01  3.354000e+01  3.355000e+01   
std    4.041494e+00  4.040265e+00  4.039350e+00  4.037499e+00  4.034610e+00   

          BidPrice3     BidPrice2  ...    AskVolume1    AskVolume2  \
count  1.171613e+06  1.171613e+06  ...  1.171613e+06  1.171613e+06   
mean   2.781345e+01  2.783078e+01  ...  4.476179e+03  4.938561e+03   
min    0.000000e+00  0.000000e+00  ...  0.000000e+00  0.000000e+00   
25%    2.696000e+01  2.698000e+01  ...  7.000000e+02  8.000000e+02   
50%    2.882000e+01  2.883000e+01  ...  1.800000e+03  2.200000e+03   
75%    2.977000e+01  2.979000e+01  ...  4.600000e+03  5.600000e+03   
max    3.356000e+01  3.358000e+01  ...  1.309300e+06  4.012300e+05   
std    4.028385e+00  4.016354e+00  ...  1.205992e+04  8.963806e+03   

         AskVolume3    AskVolume4    AskVolume5    AskVolume6    AskVolume7  \
count  1.171613e+06  1.171613e+06  1.171613e+06  1.171613e+06  1.171613e+06   
mean   5.040522e+03  5.138771e+03  5.176009e+03  5.246853e+03  5.126264e+03   
min    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    9.000000e+02  9.000000e+02  9.000000e+02  9.000000e+02  9.000000e+02   
50%    2.300000e+03  2.300000e+03  2.302000e+03  2.400000e+03  2.300000e+03   
75%    5.800000e+03  6.000000e+03  6.100000e+03  6.100000e+03  6.000000e+03   
max    3.995300e+05  3.995300e+05  3.906300e+05  3.654300e+05  3.654300e+05   
std    9.006258e+03  9.160945e+03  8.853722e+03  9.173426e+03  8.727294e+03   

         AskVolume8    AskVolume9   AskVolume10  
count  1.171613e+06  1.171613e+06  1.171613e+06  
mean   5.052338e+03  5.155902e+03  5.128731e+03  
min    0.000000e+00  0.000000e+00  0.000000e+00  
25%    9.000000e+02  9.000000e+02  9.000000e+02  
50%    2.300000e+03  2.300000e+03  2.300000e+03  
75%    5.900000e+03  6.000000e+03  5.900000e+03  
max    3.626300e+05  3.474300e+05  3.458300e+05  
std    8.829579e+03  9.022503e+03  8.784461e+03  

[8 rows x 41 columns]

In [52]:
!pip install pandas-profiling

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Preparing metadata (setup.py) ... done
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
  Using cached urllib3-2.2.3-py3-none-any.whl.metadata (6.5 kB)
  Using cached certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 27.6 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 19.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 655.9/655.9 kB 31.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 38.7 MB/s eta 0:00:00
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 28.8/28.8 MB 44.7 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 52.2 MB/s eta 0:00:00
Using cached certifi-2024.8.

In [ ]:
from ydata_profiling import ProfileReport

profile = ProfileReport(a.data, title="Pandas Profiling Report")


/opt/homebrew/Caskroom/miniconda/base/envs/lob/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]


FileNotFoundError: [Errno 2] No such file or directory: 'dataset/real_data/info/output.html'

In [57]:
profile.to_file("../dataset/real_data/info/output.html")

Export report to file: 100%|██████████| 1/1 [00:00<00:00,  5.01it/s]


In [58]:
import os 

In [60]:
os.path.basename("../dataset/real_data/sz000999-level10.csv").split('-')[0]

'sz000999'

In [1]:
from data_lobcast import *
import pandas as pd
import numpy as np

ModuleNotFoundError: No module named 'config'

In [9]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

def unbalance_data(data, window=100, step=2, dtype=np.float16):
    """
    进行时序数据采样，支持指定窗口大小和步长。
    
    参数：
        data (ndarray): 归一化后的时序数据，形状为 (num_samples, num_features)
        window (int): 采样窗口大小
        step (int): 采样步长
        dtype (numpy dtype): 结果数据类型
    
    返回：
        unbalanced_X (ndarray): 形状为 (num_windows, window, num_features) 的采样数据
    """
    if len(data) < window:
        raise ValueError("数据长度小于窗口大小，无法进行采样。")
    
    # 使用 sliding_window_view 创建滑动窗口
    windows = sliding_window_view(data, (window, data.shape[1]))[::step, 0]
    
    return windows.astype(dtype)

# 示例用法
data = np.array([i for i in range(1000)]).reshape(100,10) 
print(data)# 假设原始数据有 1000 行，5 个特征
sampled_data = unbalance_data(data, window=10, step=2)

print(sampled_data.shape)

print(sampled_data[0])
print(sampled_data[1])# 期望形状: (num_samples, 100, num_features)

d1=data[:10,:]
d2=sampled_data[0]

print(sum(d1==d2))


[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]
 [150 151 152 153 154 155 156 157 158 159]
 [160 161 162 163 164 165 166 167 168 169]
 [170 171 172 173 174 175 176 177 178 179]
 [180 181 182 183 184 185 186 187 188 189]
 [190 191 192 193 194 195 196 197 198 199]
 [200 201 202 203 204 205 206 207 208 209]
 [210 211 212 213 214 215 216 217 218 219]
 [220 221 222 223 224 225 226 227 228 229]
 [230 231 2

In [10]:
print(type(sampled_data))

<class 'numpy.ndarray'>


In [8]:
import numpy as np 
import pandas as pd
from rich import print


test_d = np.random.randint(0,100,(5,10))

print(test_d)

[[27 69 38 15 50 50 85 55 13 62]
 [56 80 22 71 97 89 43 43 86 40]
 [11 56 63 76 14 25 30 62 81 98]
 [ 1 43 11  5 78 91 12 90 27 88]
 [38 20 18 64 46 93 21 79 41  8]]

In [11]:
price_mean = np.nanmean(test_d,axis=0)
price_std = np.nanstd(test_d,axis=0)

normalized = (test_d - price_mean)/price_std
print(normalized)



[[ 0.02055639  0.73732333  0.40962167 -1.04106474 -0.24565184 -0.71519511
   1.83204285 -0.64294827 -1.25756119  0.08573643]
 [ 1.51089431  1.26398286 -0.45273974  0.827513    1.40372481  0.7078972
   0.18790183 -1.35733524  1.25068927 -0.58790693]
 [-0.80169902  0.11490753  1.75706138  0.9943503  -1.50900417 -1.62743377
  -0.32099896 -0.22622254  1.07889129  1.18806193]
 [-1.31560865 -0.50750827 -1.04561321 -1.37473934  0.73695553  0.7808763
  -1.02563083  1.44068038 -0.77652685  0.8818604 ]
 [ 0.58585698 -1.60870546 -0.6683301   0.59394078 -0.38602432  0.85385539
  -0.6733149   0.78582566 -0.29549252 -1.56775182]]